Signup page linked to send request to backend
AgnesCroteau/SOEN-341-PROJECT-GROUP-K pull request #67
Opened 2022-03-21 05:08 UTC by AgnesCroteau

Link sign up page to a request that will write a new account in the database

2022-03-21 20:08 UTC, cnfrancis commented
The backend barely change, front end seems good to go.

2022-03-22 01:56 UTC, nolanbastien requested changes
Good work Agnès ! :)

2022-03-22 01:56 UTC, nolanbastien commented on backend/server.js
> +const cors = require('cors')
This is a duplicate of line 7.

Remove it ! :P

2022-03-22 01:56 UTC, nolanbastien commented on backend/server.js
> +app.use(cors());
This is a duplicate of line 10.

2022-03-22 01:56 UTC, nolanbastien commented on frontend/src/Components/Pages/SignUpPage.js
> +                // TODO: User created successfully, redirect to correct page here
To redirect to home page you can use the same function as on line 48: 

`navigate('/')` 

2022-03-22 02:02 UTC, cnfrancis approved these changes

2022-03-25 00:41 UTC, merged